export enum Role {
  ADMIN = 'ADMIN',
  SALES_REP = 'SALES_REP',
  TERRITORY_DISTRIBUTOR = 'TERRITORY_DISTRIBUTOR',
  SHOP_OWNER = 'SHOP_OWNER',
  DEMAND_PLANNER = 'DEMAND_PLANNER',
  REGIONAL_MANAGER = 'REGIONAL_MANAGER',
}
